### ISSUE TITLE
[Documentation] Sidebar for Navigation

### ISSUE THREAD

**Issue by teamsuperpanda** [chrismaltby/gb-studio-site#24]
I had a look and think you are using Hugo for the documentation.
I’m not familiar but there looks like an option to implement a side bar.

Rather than clicking on the next section and the bottom of each page you could have a side bar for quick jumping.

Just an idea...

**Comment by DeerTears** [comment]
I like this idea, all of the pages have headers in their markdown files which makes them ripe for a table of contents, but I wasn't sure if it was worth it to add that table of contents to the beginning of every page. A sidebar would be a great place to put links to each header (for example, https://www.gbstudio.dev/docs/scripting/#music-events takes you to the music-events header of the Scripting page)

**Comment by DeerTears** [comment]
Last I checked there was no sidebar, and now I see one exists! Thank you so much Chris for adding this!

**Comment by chrismaltby** [comment]
Hah, literally came here to mention this and you got here first :-) I had to make a few changes to the music page to make the sub headers `h2`s and `h3`s but I think this issue is resolved now.
