### ISSUE TITLE
Please make it easier to change language to english

### ISSUE THREAD

**Issue by baardbi** [chrismaltby/gb-studio-site#48]
Please make an option to change the language setting. The app defaults to norwegian (which is my Windows language). The norwegian translation is really bad, and I would much rather have a proper english GUI (menus and so on). If this isn't possible then I would very much like to know how I can change the language file in my GBstudio installation. Thank you. The app is great.

**Comment by pau-tomas** [comment]
It's possible to change the language via the "View > Language" menu.

**Comment by baardbi** [comment]
Thank you very much for that quick reply. It works great.
